### ISSUE TITLE
[VR] override.cfg gets deleted when launching the game and VR doesn't work

### ISSUE THREAD

**Issue by Slooshie1** [ScientificGuy/BuckshotRouletteMods#1]
The only mod I have in the mods folder is the Virtual Reality mod. When launching the game with the brml.bat file through SteamVR, the override.cfg file gets deleted immediately and the game launches in normal 2D mode. No matter how many times I put the file back in Documents/Buckshot Roulette where the exe and bat files are, it keeps getting deleted upon launch. I am playing on v1.2.2 with Virtual Reality v0.0.1

**Comment by MSLaFaver** [comment]
BRML 2.0.0 does not support VirtualReality 0.0.1. The source code and the readme have not been updated for the Steam version. I edited the readme to reflect this, sorry for the confusion.

If you are running BRML 2.0.0, this mod might still work for you. Either place the `override.cfg` file in the `override` folder or in the VirtualReality .zip file. Otherwise, this mod is only confirmed with BRML 1.1.1.

**Comment by Slooshie1** [comment]
Thank you for that clarification. I placed `override.cfg` in `override` and the game seems to render in VR but unfortunately breaks upon clicking start. Can we expect the VR mod to receive an update for BRML 2.0.0 sometime in the future?

**Comment by MSLaFaver** [comment]
Working on it, have a few other priorities first but I’ll see what I can do.
